"""
AI ARX Regime

Generated by strategies/train_ai_arx_regime.py.
The model uses autoregressive returns, support/resistance, regime features,
volume, and trailing news sentiment.
"""

import numpy as np
import pandas as pd


STRATEGY_NAME = "AI ARX Regime"
VERSION = "0.1"
DESCRIPTION = "Long-only ARX/regime strategy with 5-day and 10-day AI forecasts."
RETURN_LAGS = tuple(range(1, 21))
FEATURE_COLUMNS = [
    "return_lag_1",
    "return_lag_2",
    "return_lag_3",
    "return_lag_4",
    "return_lag_5",
    "return_lag_6",
    "return_lag_7",
    "return_lag_8",
    "return_lag_9",
    "return_lag_10",
    "return_lag_11",
    "return_lag_12",
    "return_lag_13",
    "return_lag_14",
    "return_lag_15",
    "return_lag_16",
    "return_lag_17",
    "return_lag_18",
    "return_lag_19",
    "return_lag_20",
    "return_5",
    "return_10",
    "return_20",
    "return_60",
    "return_120",
    "volatility_10",
    "volatility_20",
    "volatility_60",
    "range_pct",
    "sma_10_gap",
    "sma_20_gap",
    "sma_50_gap",
    "sma_100_gap",
    "sma_20_slope_10",
    "sma_50_slope_20",
    "range_position_20",
    "range_position_60",
    "range_position_120",
    "dist_high_20",
    "dist_high_60",
    "dist_high_120",
    "dist_low_20",
    "dist_low_60",
    "dist_low_120",
    "drawdown_20",
    "drawdown_60",
    "drawdown_120",
    "breakout_20",
    "breakout_60",
    "breakdown_20",
    "volume_ratio_20",
    "volume_ratio_60",
    "rsi_14",
    "regime_score",
    "news_count_7d",
    "direct_news_count_7d",
    "avg_signed_sentiment_7d",
    "sentiment_intensity_7d",
    "news_count_30d",
    "direct_news_count_30d",
    "avg_signed_sentiment_30d",
    "sentiment_intensity_30d"
]
FEATURE_MEANS = np.array([0.001598614675, 0.001720663171, 0.001651335711, 0.001612375205, 0.001515781008, 0.001433543239, 0.001399608907, 0.001451402819, 0.001434831189, 0.001350298696, 0.001325104619, 0.001353246618, 0.001264446972, 0.001308916101, 0.001202795185, 0.00141797503, 0.001416620766, 0.001310013781, 0.001333018277, 0.001154373759, 0.007557212895, 0.014201504894, 0.026077784286, 0.078554120453, 0.119158833567, 0.023293771256, 0.02383249715, 0.023717222756, 0.028550581345, 0.005385623814, 0.010932905204, 0.024781068219, 0.046206856547, 0.010324335581, 0.015796136789, 0.585400359717, 0.577228171907, 0.549059419118, -0.059872225139, -0.090477147969, -0.103449140372, 0.106562141093, 0.215993093349, 0.350432314777, -0.059872225139, -0.090477147969, -0.103449140372, 0.097488038278, 0.071770334928, 0.041267942584, 0.035098788355, 0.053360897826, 0.545109256965, 2.847488038278, 53.903110047847, 53.903110047847, 0.158228872426, 0.248149048232, 222.701555023923, 222.701555023923, 0.15684619119, 0.246856846178], dtype=float)
FEATURE_STDS = np.array([0.028322857882, 0.028121867633, 0.028104876398, 0.028074870058, 0.02802611567, 0.027938233887, 0.027930327183, 0.027908777313, 0.027907879143, 0.027871630353, 0.027861005972, 0.027850742094, 0.027749154191, 0.027719887856, 0.027664020916, 0.027468788427, 0.027452636357, 0.027306121663, 0.027263379011, 0.026608707412, 0.059819150155, 0.080671000176, 0.118889551323, 0.197075642652, 0.262736029472, 0.01628301579, 0.014895115607, 0.013580102983, 0.02097590289, 0.043442669306, 0.063787866064, 0.105916393373, 0.139643008156, 0.052140881579, 0.066575573786, 0.313013730637, 0.343204309851, 0.357593542047, 0.061940563515, 0.098239873553, 0.106725121039, 0.097295749252, 0.194837502773, 0.336454288742, 0.061940563515, 0.098239873553, 0.106725121039, 0.296621173672, 0.258107252809, 0.198909274542, 0.46074227801, 0.519054360788, 0.164294396235, 2.11681995087, 33.376659178046, 33.376659178046, 0.088940678555, 0.104913803836, 129.808383984263, 129.808383984263, 0.075321644366, 0.099241023123], dtype=float)
MODEL_5D_WEIGHTS = np.array([-0.018973344108, -0.091817328256, -0.018928651945, 0.005081094522, 0.026269323688, 0.050025349436, 0.052113519148, 0.004022764201, 0.033832649146, 0.054158258682, 0.057037558485, -0.015804249247, -0.033708939248, -0.059710628533, -0.001375669396, -0.052621166571, -0.000668267183, 0.003508063931, 0.037431484576, 0.035535645844, -0.058685777017, 0.008191148978, -0.01462593119, -0.049848979639, 0.006044367249, 0.06464891124, 0.018770532842, 0.031657340375, -0.035586332739, -0.044584542624, -0.008541684829, 0.022758013928, -0.019181234157, 0.040607739691, 0.011764932616, 0.000490066791, 0.001141513103, 0.088399491014, 0.021207705703, 0.00263003881, -0.108745378698, -0.05333553388, 0.065306136773, 0.070619945686, 0.021207705703, 0.00263003881, -0.108745378698, 0.009457683448, -0.016675812408, 0.032976129782, 0.015857503187, -0.077387964506, 0.02705288048, 0.030928346623, 0.055319320211, 0.055319320211, -0.011800750839, 0.02641503346, -0.045111937875, -0.045111937875, -0.012531592691, 0.004698921971], dtype=float)
MODEL_5D_BIAS = 0.000144055325
MODEL_10D_WEIGHTS = np.array([0.014069283133, -0.049308083153, 0.008848075083, 0.049038149018, -0.020007656798, 0.006077545214, 0.043913324621, -0.013568631286, -0.000415466222, 0.032968550806, 0.025516367199, -0.005939077391, -0.015293695435, -0.018000311243, -0.003331317373, 0.013452883548, 0.029074938715, 0.02074496663, 0.03929991542, 0.039512649902, -0.037550807961, -0.029265148105, 0.00221284083, -0.069429630365, -0.039999143361, 0.06563126001, 0.012406879132, 0.034880772145, -0.001272297964, -0.056829736542, -0.026249939094, 0.025430575216, -0.041262310669, 0.068617465442, -0.031205915629, -0.004155818608, 0.020248103782, 0.14663143015, 0.057856821613, -0.009552231518, -0.166823793357, -0.036713652896, 0.129794136897, 0.070904779214, 0.057856821613, -0.009552231518, -0.166823793357, -0.029734312536, -0.046400651113, -0.000432595795, 0.0588984591, -0.062660845021, 0.040881246147, 0.063237315049, 0.048702319832, 0.048702319832, 0.046093980368, -0.002526409569, -0.067665202369, -0.067665202369, 0.023213553656, -0.025696906766], dtype=float)
MODEL_10D_BIAS = 0.001869992552
ENTRY_THRESHOLD_5D = 0.4500
ENTRY_THRESHOLD_10D = 0.4700
EXIT_THRESHOLD_5D = 0.3500
EXIT_THRESHOLD_10D = 0.3500
NEWS_LOOKBACK_SHORT_DAYS = 7
NEWS_LOOKBACK_LONG_DAYS = 30
TARGET_5D_BPS = 75.00
TARGET_10D_BPS = 125.00


def _sigmoid(values):
    values = np.clip(values, -40.0, 40.0)
    return 1.0 / (1.0 + np.exp(-values))


def _signed_sentiment(sentiment):
    labels = sentiment["label"].fillna("neutral")
    scores = sentiment["score"].fillna(0.0).astype(float)
    return np.select(
        [labels.eq("positive"), labels.eq("negative")],
        [scores, -scores],
        default=0.0,
    )


def _aggregate_news_window(window, suffix):
    if window.empty:
        return {
            f"news_count_{suffix}": 0.0,
            f"direct_news_count_{suffix}": 0.0,
            f"avg_signed_sentiment_{suffix}": 0.0,
            f"sentiment_intensity_{suffix}": 0.0,
        }
    return {
        f"news_count_{suffix}": float(len(window)),
        f"direct_news_count_{suffix}": float(window["relation_type"].eq("direct").sum()),
        f"avg_signed_sentiment_{suffix}": float(window["signed_sentiment"].mean()),
        f"sentiment_intensity_{suffix}": float(window["signed_sentiment"].abs().mean()),
    }


def _news_features(candles, news, sentiment):
    if news is None or not hasattr(news, "empty") or news.empty:
        news = pd.DataFrame(columns=["id", "available_at", "relation_type"])
    else:
        news = news.copy()
    if sentiment is None or not hasattr(sentiment, "empty") or sentiment.empty:
        sentiment = pd.DataFrame(
            columns=["article_id", "label", "score", "positive", "neutral", "negative"]
        )
    else:
        sentiment = sentiment.copy()
    if "available_at" in news:
        news["available_at"] = pd.to_datetime(news["available_at"], utc=True, errors="coerce")
    if "id" not in news:
        news["id"] = None
    if "relation_type" not in news:
        news["relation_type"] = "direct"
    if "article_id" not in sentiment:
        sentiment["article_id"] = None
    for column in ["positive", "neutral", "negative", "score"]:
        if column not in sentiment:
            sentiment[column] = 0.0
    if "label" not in sentiment:
        sentiment["label"] = "neutral"
    if not sentiment.empty:
        sentiment["signed_sentiment"] = _signed_sentiment(sentiment)

    rows = []
    for timestamp in candles["timestamp"]:
        cutoff = pd.to_datetime(timestamp, utc=True)
        if news.empty or "available_at" not in news:
            short_news = news.iloc[0:0]
            long_news = news.iloc[0:0]
        else:
            short_start = cutoff - pd.Timedelta(days=NEWS_LOOKBACK_SHORT_DAYS)
            long_start = cutoff - pd.Timedelta(days=NEWS_LOOKBACK_LONG_DAYS)
            short_news = news[
                (news["available_at"] <= cutoff) & (news["available_at"] > short_start)
            ]
            long_news = news[
                (news["available_at"] <= cutoff) & (news["available_at"] > long_start)
            ]

        def attach_sentiment(news_window):
            if news_window.empty:
                return news_window.assign(signed_sentiment=pd.Series(dtype=float))
            article_ids = set(news_window["id"].dropna().tolist())
            window_sentiment = sentiment[sentiment["article_id"].isin(article_ids)]
            if window_sentiment.empty:
                return news_window.assign(signed_sentiment=0.0)
            signed_value = float(window_sentiment["signed_sentiment"].mean())
            intensity_value = float(window_sentiment["signed_sentiment"].abs().mean())
            out = news_window.copy()
            out["signed_sentiment"] = signed_value
            out["_sentiment_intensity"] = intensity_value
            return out

        short_window = attach_sentiment(short_news)
        long_window = attach_sentiment(long_news)
        row = _aggregate_news_window(short_window, "7d")
        row.update(_aggregate_news_window(long_window, "30d"))
        if "_sentiment_intensity" in short_window:
            row["sentiment_intensity_7d"] = float(short_window["_sentiment_intensity"].mean())
        if "_sentiment_intensity" in long_window:
            row["sentiment_intensity_30d"] = float(long_window["_sentiment_intensity"].mean())
        rows.append(row)
    return pd.DataFrame(rows, index=candles.index)


def _safe_range_position(close, low, high):
    width = (high - low).replace(0, np.nan)
    return ((close - low) / width).clip(0.0, 1.0)


def _calculate_features(candles, news, sentiment):
    df = candles.copy()
    df["_strategy_timestamp"] = pd.to_datetime(df["timestamp"], utc=True)
    df = df.sort_values("_strategy_timestamp")
    df["timestamp"] = df["_strategy_timestamp"]
    close = df["close"].astype(float)
    high = df["high"].astype(float)
    low = df["low"].astype(float)
    volume = df["volume"].astype(float).replace(0, np.nan)
    returns = close.pct_change()

    features = pd.DataFrame(index=df.index)
    for lag in RETURN_LAGS:
        features[f"return_lag_{lag}"] = returns.shift(lag)
    for window in (5, 10, 20, 60, 120):
        features[f"return_{window}"] = close / close.shift(window) - 1.0
    features["volatility_10"] = returns.rolling(10, min_periods=5).std()
    features["volatility_20"] = returns.rolling(20, min_periods=8).std()
    features["volatility_60"] = returns.rolling(60, min_periods=20).std()
    features["range_pct"] = (high - low) / close

    sma_10 = close.rolling(10, min_periods=5).mean()
    sma_20 = close.rolling(20, min_periods=8).mean()
    sma_50 = close.rolling(50, min_periods=20).mean()
    sma_100 = close.rolling(100, min_periods=40).mean()
    features["sma_10_gap"] = close / sma_10 - 1.0
    features["sma_20_gap"] = close / sma_20 - 1.0
    features["sma_50_gap"] = close / sma_50 - 1.0
    features["sma_100_gap"] = close / sma_100 - 1.0
    features["sma_20_slope_10"] = sma_20 / sma_20.shift(10) - 1.0
    features["sma_50_slope_20"] = sma_50 / sma_50.shift(20) - 1.0

    previous_high_20 = high.rolling(20, min_periods=8).max().shift(1)
    previous_high_60 = high.rolling(60, min_periods=20).max().shift(1)
    previous_low_20 = low.rolling(20, min_periods=8).min().shift(1)
    for window in (20, 60, 120):
        rolling_high = high.rolling(window, min_periods=max(8, window // 3)).max()
        rolling_low = low.rolling(window, min_periods=max(8, window // 3)).min()
        features[f"range_position_{window}"] = _safe_range_position(close, rolling_low, rolling_high)
        features[f"dist_high_{window}"] = close / rolling_high - 1.0
        features[f"dist_low_{window}"] = close / rolling_low - 1.0
        features[f"drawdown_{window}"] = close / rolling_high - 1.0
    features["breakout_20"] = (close > previous_high_20).astype(float)
    features["breakout_60"] = (close > previous_high_60).astype(float)
    features["breakdown_20"] = (close < previous_low_20).astype(float)
    features["volume_ratio_20"] = volume / volume.rolling(20, min_periods=8).mean() - 1.0
    features["volume_ratio_60"] = volume / volume.rolling(60, min_periods=20).mean() - 1.0

    delta = close.diff()
    gain = delta.clip(lower=0).rolling(14, min_periods=5).mean()
    loss = (-delta.clip(upper=0)).rolling(14, min_periods=5).mean()
    rs = gain / loss.replace(0, np.nan)
    features["rsi_14"] = (100.0 - (100.0 / (1.0 + rs))).fillna(50.0) / 100.0
    trend_checks = pd.concat(
        [
            (close > sma_50).astype(float),
            (sma_20 > sma_50).astype(float),
            (features["sma_50_slope_20"] > 0).astype(float),
            (features["range_position_60"] > 0.45).astype(float),
            (features["return_20"] > 0).astype(float),
        ],
        axis=1,
    )
    features["regime_score"] = trend_checks.sum(axis=1)
    features = pd.concat([features, _news_features(df, news, sentiment)], axis=1)
    return features[FEATURE_COLUMNS].replace([np.inf, -np.inf], np.nan).fillna(0.0)


def run(ctx):
    candles = ctx.candles.copy()
    if candles.empty:
        return {"entries": [], "exits": [], "markers": [], "debug": {"reason": "no candles"}}

    features = _calculate_features(candles, ctx.news, ctx.sentiment)
    x_values = ((features.values - FEATURE_MEANS) / FEATURE_STDS).astype(float)
    probability_5d = pd.Series(
        _sigmoid(x_values @ MODEL_5D_WEIGHTS + MODEL_5D_BIAS),
        index=features.index,
        name="probability_5d",
    )
    probability_10d = pd.Series(
        _sigmoid(x_values @ MODEL_10D_WEIGHTS + MODEL_10D_BIAS),
        index=features.index,
        name="probability_10d",
    )

    trend_ok = (
        (features["regime_score"] >= 3.0)
        & (features["sma_20_gap"] > -0.03)
        & (features["range_position_60"] > 0.28)
        & (features["breakdown_20"] < 0.5)
    )
    risk_ok = (features["volatility_20"] < 0.07) | (features["regime_score"] >= 4.0)
    entries = (
        (probability_5d >= ENTRY_THRESHOLD_5D)
        & (probability_10d >= ENTRY_THRESHOLD_10D)
        & trend_ok
        & risk_ok
    )
    exits = (
        (probability_5d <= EXIT_THRESHOLD_5D)
        | (probability_10d <= EXIT_THRESHOLD_10D)
        | (features["breakdown_20"] > 0.5)
        | ((features["sma_20_gap"] < -0.045) & (features["regime_score"] <= 2.0))
    )

    entries = entries.fillna(False)
    exits = exits.fillna(False)
    if len(entries):
        entries.iloc[:30] = False

    markers = []
    high_confidence = probability_5d[
        (probability_5d >= max(ENTRY_THRESHOLD_5D + 0.08, 0.65))
        & (probability_10d >= ENTRY_THRESHOLD_10D)
    ]
    for timestamp, probability in high_confidence.tail(8).items():
        markers.append({
            "timestamp": timestamp,
            "type": "signal",
            "label": f"ARX {probability:.0%}",
            "color": "#2563eb",
        })

    return {
        "entries": entries,
        "exits": exits,
        "markers": markers,
        "debug": {
            "strategy": STRATEGY_NAME,
            "version": VERSION,
            "model": "two_horizon_logistic_arx",
            "trained_symbols": ["AAPL", "AMD", "AMZN", "GOOGL", "META", "NVDA", "SPY", "TSLA"],
            "training_start": "2025-01-01",
            "training_end": "2025-12-31",
            "target_5d_bps": TARGET_5D_BPS,
            "target_10d_bps": TARGET_10D_BPS,
            "entry_threshold_5d": ENTRY_THRESHOLD_5D,
            "entry_threshold_10d": ENTRY_THRESHOLD_10D,
            "exit_threshold_5d": EXIT_THRESHOLD_5D,
            "exit_threshold_10d": EXIT_THRESHOLD_10D,
            "bars": int(len(candles)),
            "entry_count": int(entries.sum()),
            "exit_count": int(exits.sum()),
            "latest_probability_5d": float(probability_5d.iloc[-1]),
            "latest_probability_10d": float(probability_10d.iloc[-1]),
            "latest_regime_score": float(features["regime_score"].iloc[-1]),
            "mean_probability_5d": float(probability_5d.mean()),
            "mean_probability_10d": float(probability_10d.mean()),
        },
    }
