"""
AI Sentiment Momentum

Generated by strategies/train_ai_sentiment_momentum.py.
The model is a small logistic-regression classifier trained on 2025 daily data
for AAPL, GOOGL, and TSLA.
"""

import numpy as np
import pandas as pd


STRATEGY_NAME = "AI Sentiment Momentum"
VERSION = "0.1"
DESCRIPTION = "Long-only AI strategy using price momentum, volatility, volume, and trailing news sentiment."
FEATURE_COLUMNS = [
    "return_1",
    "return_3",
    "return_5",
    "return_10",
    "sma_5_gap",
    "sma_10_gap",
    "sma_20_gap",
    "volatility_5",
    "volatility_10",
    "range_pct",
    "volume_ratio_5",
    "volume_ratio_20",
    "momentum_5",
    "rsi_14",
    "news_count",
    "direct_news_count",
    "avg_positive",
    "avg_negative",
    "avg_signed_sentiment",
    "sentiment_intensity"
]
FEATURE_MEANS = np.array([0.001525009842, 0.004147789035, 0.006647690967, 0.01192762049, 0.002181474701, 0.00447297648, 0.008472355944, 0.023803240013, 0.025070212486, 0.031732982003, 0.011680869632, 0.032733791504, 0.001423535926, 0.538883270458, 68.591706539075, 68.591706539075, 0.33374562616, 0.235570969172, 0.164242116133, 0.275848962109], dtype=float)
FEATURE_STDS = np.array([0.029573823461, 0.050739195826, 0.062925998819, 0.083131776192, 0.0316929831, 0.04541925384, 0.065407720333, 0.018014760567, 0.015985236873, 0.022327046408, 0.311252362004, 0.440654817383, 0.012500067244, 0.167718658724, 24.960047082433, 24.960047082433, 0.031677891642, 0.016267023394, 0.061157862491, 0.046731374998], dtype=float)
MODEL_WEIGHTS = np.array([-0.070395993084, 0.133944282619, -0.023461159375, -0.004658183677, 0.091126809328, -0.077401940344, -0.053371305268, -0.167778964778, 0.19977473811, 0.013788904872, 0.029397685947, 0.034256241425, -0.115705578128, 0.05982182962, 0.008573665498, 0.008573665498, 0.126112292017, -0.034743398807, 0.002052080048, -0.008302515026], dtype=float)
MODEL_BIAS = -0.001170344448
ENTRY_THRESHOLD = 0.4900
EXIT_THRESHOLD = 0.3700
NEWS_LOOKBACK_DAYS = 7
TARGET_RETURN_BPS = 20.00


def _signed_sentiment(sentiment):
    labels = sentiment["label"].fillna("neutral")
    scores = sentiment["score"].fillna(0.0).astype(float)
    return np.select(
        [labels.eq("positive"), labels.eq("negative")],
        [scores, -scores],
        default=0.0,
    )


def _news_features(candles, news, sentiment):
    if news is None or not hasattr(news, "empty") or news.empty:
        news = pd.DataFrame(columns=["id", "available_at", "relation_type"])
    else:
        news = news.copy()
    if sentiment is None or not hasattr(sentiment, "empty") or sentiment.empty:
        sentiment = pd.DataFrame(
            columns=["article_id", "label", "score", "positive", "neutral", "negative"]
        )
    else:
        sentiment = sentiment.copy()

    if "available_at" in news:
        news["available_at"] = pd.to_datetime(news["available_at"], utc=True, errors="coerce")
    if "id" not in news:
        news["id"] = None
    if "relation_type" not in news:
        news["relation_type"] = "direct"
    if "article_id" not in sentiment:
        sentiment["article_id"] = None
    for column in ["positive", "neutral", "negative", "score"]:
        if column not in sentiment:
            sentiment[column] = 0.0
    if "label" not in sentiment:
        sentiment["label"] = "neutral"

    if not sentiment.empty:
        sentiment["signed_sentiment"] = _signed_sentiment(sentiment)

    rows = []
    for timestamp in candles["timestamp"]:
        cutoff = pd.to_datetime(timestamp, utc=True)
        start = cutoff - pd.Timedelta(days=NEWS_LOOKBACK_DAYS)
        if news.empty or "available_at" not in news:
            window_news = news.iloc[0:0]
        else:
            window_news = news[
                (news["available_at"] <= cutoff) & (news["available_at"] > start)
            ]
        if window_news.empty:
            rows.append({
                "news_count": 0.0,
                "direct_news_count": 0.0,
                "avg_positive": 0.0,
                "avg_negative": 0.0,
                "avg_signed_sentiment": 0.0,
                "sentiment_intensity": 0.0,
            })
            continue
        article_ids = set(window_news["id"].dropna().tolist())
        window_sentiment = sentiment[sentiment["article_id"].isin(article_ids)]
        if window_sentiment.empty:
            rows.append({
                "news_count": float(len(window_news)),
                "direct_news_count": float(window_news["relation_type"].eq("direct").sum()),
                "avg_positive": 0.0,
                "avg_negative": 0.0,
                "avg_signed_sentiment": 0.0,
                "sentiment_intensity": 0.0,
            })
            continue
        rows.append({
            "news_count": float(len(window_news)),
            "direct_news_count": float(window_news["relation_type"].eq("direct").sum()),
            "avg_positive": float(window_sentiment["positive"].astype(float).mean()),
            "avg_negative": float(window_sentiment["negative"].astype(float).mean()),
            "avg_signed_sentiment": float(window_sentiment["signed_sentiment"].mean()),
            "sentiment_intensity": float(window_sentiment["signed_sentiment"].abs().mean()),
        })
    return pd.DataFrame(rows, index=candles.index)


def _calculate_features(candles, news, sentiment):
    df = candles.copy()
    df["_strategy_timestamp"] = pd.to_datetime(df["timestamp"], utc=True)
    df = df.sort_values("_strategy_timestamp")
    df["timestamp"] = df["_strategy_timestamp"]
    close = df["close"].astype(float)
    volume = df["volume"].astype(float).replace(0, np.nan)
    returns = close.pct_change()

    features = pd.DataFrame(index=df.index)
    features["return_1"] = returns
    features["return_3"] = close / close.shift(3) - 1.0
    features["return_5"] = close / close.shift(5) - 1.0
    features["return_10"] = close / close.shift(10) - 1.0
    features["sma_5_gap"] = close / close.rolling(5, min_periods=2).mean() - 1.0
    features["sma_10_gap"] = close / close.rolling(10, min_periods=3).mean() - 1.0
    features["sma_20_gap"] = close / close.rolling(20, min_periods=5).mean() - 1.0
    features["volatility_5"] = returns.rolling(5, min_periods=3).std()
    features["volatility_10"] = returns.rolling(10, min_periods=5).std()
    features["range_pct"] = (df["high"].astype(float) - df["low"].astype(float)) / close
    features["volume_ratio_5"] = volume / volume.rolling(5, min_periods=2).mean() - 1.0
    features["volume_ratio_20"] = volume / volume.rolling(20, min_periods=5).mean() - 1.0
    features["momentum_5"] = returns.rolling(5, min_periods=3).mean()

    delta = close.diff()
    gain = delta.clip(lower=0).rolling(14, min_periods=5).mean()
    loss = (-delta.clip(upper=0)).rolling(14, min_periods=5).mean()
    rs = gain / loss.replace(0, np.nan)
    features["rsi_14"] = (100.0 - (100.0 / (1.0 + rs))).fillna(50.0) / 100.0

    features = pd.concat([features, _news_features(df, news, sentiment)], axis=1)
    return features[FEATURE_COLUMNS].replace([np.inf, -np.inf], np.nan).fillna(0.0)


def _sigmoid(values):
    values = np.clip(values, -40.0, 40.0)
    return 1.0 / (1.0 + np.exp(-values))


def run(ctx):
    candles = ctx.candles.copy()
    if candles.empty:
        return {"entries": [], "exits": [], "markers": [], "debug": {"reason": "no candles"}}

    features = _calculate_features(candles, ctx.news, ctx.sentiment)
    x_values = ((features.values - FEATURE_MEANS) / FEATURE_STDS).astype(float)
    probabilities = pd.Series(
        _sigmoid(x_values @ MODEL_WEIGHTS + MODEL_BIAS),
        index=candles.index,
        name="ai_probability",
    )

    trend_filter = features["sma_5_gap"] > -0.015
    volatility_filter = features["volatility_10"] < 0.055
    entries = (probabilities >= ENTRY_THRESHOLD) & trend_filter & volatility_filter
    exits = (probabilities <= EXIT_THRESHOLD) | (features["return_3"] < -0.035)

    entries = entries.fillna(False)
    exits = exits.fillna(False)
    if len(entries):
        entries.iloc[:20] = False

    markers = []
    high_confidence = probabilities[probabilities >= max(ENTRY_THRESHOLD + 0.08, 0.65)]
    for timestamp, probability in high_confidence.tail(8).items():
        markers.append({
            "timestamp": timestamp,
            "type": "signal",
            "label": f"AI {probability:.0%}",
            "color": "#2563eb",
        })

    return {
        "entries": entries,
        "exits": exits,
        "markers": markers,
        "debug": {
            "strategy": STRATEGY_NAME,
            "version": VERSION,
            "model": "logistic_regression_numpy",
            "trained_symbols": ["AAPL", "GOOGL", "TSLA"],
            "training_start": "2025-01-01",
            "training_end": "2025-12-31",
            "target_return_bps": TARGET_RETURN_BPS,
            "entry_threshold": ENTRY_THRESHOLD,
            "exit_threshold": EXIT_THRESHOLD,
            "bars": int(len(candles)),
            "entry_count": int(entries.sum()),
            "exit_count": int(exits.sum()),
            "latest_probability": float(probabilities.iloc[-1]),
            "mean_probability": float(probabilities.mean()),
        },
    }
