export const defaultStrategy = `import numpy as np
import pandas as pd


STRATEGY_NAME = "SMA crossover"
VERSION = "1.0"
DESCRIPTION = "Long-only moving average crossover with optional news-risk markers."


def crossover_up(fast: pd.Series, slow: pd.Series) -> pd.Series:
    return (fast > slow) & (fast.shift(1) <= slow.shift(1))


def crossover_down(fast: pd.Series, slow: pd.Series) -> pd.Series:
    return (fast < slow) & (fast.shift(1) >= slow.shift(1))


def run(ctx):
    # ctx.candles is a pandas DataFrame with the loaded candles:
    # timestamp, open, high, low, close, volume, symbol, timeframe, source.
    candles = ctx.candles.copy()

    # Use each candle close to calculate the signals.
    close = candles["close"]

    # Fast and slow moving averages. In 5Min, 10 candles = 50 minutes
    # and 25 candles = 125 minutes. In 1Day, they are 10 and 25 days.
    fast = close.rolling(10).mean()
    slow = close.rolling(25).mean()

    # Buy when the fast average crosses above the slow average.
    # shift(1) compares against the previous candle to detect the crossover,
    # not just whether fast is above slow.
    entries = crossover_up(fast, slow)

    # Sell when the fast average crosses below the slow average.
    # The engine can also close through Stop % or Take % from the UI.
    exits = crossover_down(fast, slow)

    # markers lets you draw extra annotations on the chart.
    # The main buys/sells are generated by the engine from entries/exits.
    markers = []

    # Example: if there is strong negative news sentiment, draw an
    # informational marker at the end of the series.
    if len(getattr(ctx, "sentiment", [])) > 0:
        recent_negative = ctx.sentiment[
            (ctx.sentiment["label"] == "negative") & (ctx.sentiment["score"] > 0.55)
        ]
        if len(recent_negative) > 0:
            markers.append({
                "timestamp": candles["timestamp"].iloc[-1],
                "type": "news",
                "label": "News risk",
                "color": "#d64545",
            })

    # The backtester expects entries/exits as booleans aligned to candles.
    # markers and debug are optional.
    return {
        "entries": entries,
        "exits": exits,
        "markers": markers,
        "debug": {
            "strategy": STRATEGY_NAME,
            "version": VERSION,
            "bars": int(len(candles)),
            "entry_count": int(np.asarray(entries.fillna(False)).sum()),
            "exit_count": int(np.asarray(exits.fillna(False)).sum()),
        },
    }
`;
