export const defaultStrategy = `def run(ctx):
    # ctx.candles is a pandas DataFrame with the loaded candles:
    # timestamp, open, high, low, close, volume, symbol, timeframe, source.
    candles = ctx.candles

    # Use each candle close to calculate the signals.
    close = candles["close"]

    # Fast and slow moving averages. In 5Min, 10 candles = 50 minutes
    # and 25 candles = 125 minutes. In 1Day, they are 10 and 25 days.
    fast = close.rolling(10).mean()
    slow = close.rolling(25).mean()

    # Buy when the fast average crosses above the slow average.
    # shift(1) compares against the previous candle to detect the crossover,
    # not just whether fast is above slow.
    entries = (fast > slow) & (fast.shift(1) <= slow.shift(1))

    # Sell when the fast average crosses below the slow average.
    # The engine can also close through Stop % or Take % from the UI.
    exits = (fast < slow) & (fast.shift(1) >= slow.shift(1))

    # markers lets you draw extra annotations on the chart.
    # The main buys/sells are generated by the engine from entries/exits.
    markers = []

    # Example: if there is strong negative news sentiment, draw an
    # informational marker at the end of the series.
    if len(getattr(ctx, "sentiment", [])) > 0:
        recent_negative = ctx.sentiment[
            (ctx.sentiment["label"] == "negative") & (ctx.sentiment["score"] > 0.55)
        ]
        if len(recent_negative) > 0:
            markers.append({
                "timestamp": candles["timestamp"].iloc[-1],
                "type": "news",
                "label": "News risk",
                "color": "#d64545",
            })

    # The backtester expects entries/exits as booleans aligned to candles.
    # markers is optional.
    return {
        "entries": entries,
        "exits": exits,
        "markers": markers,
    }
`;
